# Generated by Django 2.0.5 on 2018-05-28 14:17

from django.db import migrations, models

import utils.user_img


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180528_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img_for_user',
            field=models.ImageField(height_field=100, upload_to=utils.user_img.artical_img_path, width_field=100),
        ),
    ]
