# Generated by Django 2.0.5 on 2018-05-28 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180528_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.CharField(max_length=255, verbose_name='Reviewer name')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.articalimg', verbose_name='Picture')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
