# Generated by Django 2.0.5 on 2018-05-31 16:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
