# Generated by Django 2.0.5 on 2018-06-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20180606_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github_id',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
