# Generated by Django 2.0.5 on 2018-06-07 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20180608_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='github',
            old_name='username',
            new_name='user',
        ),
    ]
