# Generated by Django 2.0.5 on 2018-06-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20180608_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='github',
            name='user',
        ),
        migrations.DeleteModel(
            name='GitHub',
        ),
    ]
